[general]
seed = 20180803
checkpoint_every = 1
print_every = 10
cuda = true
checkpoint = ""
use_keras_weights = true
freeze_conv = false

[network]
rnn_size = 256
dropout = 0.5

[train]
num_workers = 8
curriculum = 0.925
lr = 3e-4
nepochs = 10000

[dataset]
datapath = "/train/GRID/data/lipnet_crop_sd_100x50"
alignpath = "/train/GRID/align"
bs = 40
test_overlapped = false
temporal_jitter = 0.05
normalise = true
frame_rate = 25
min_timesteps = 2
max_timesteps = 75
mode_img = "mouth"
debug = false
list_overlapped = "overlapped_list.json"
use_words = true
size = [3, 50, 100]
mode_sub = true
